[base16]
color00 = "#282A36"
color01 = "#FF5555"
color02 = "#50FA7B"
color03 = "#F1FA8C"
color04 = "#BD93F9"
color05 = "#FF79C6"
color06 = "#8BE9FD"
color07 = "#F8F8F2"
color10 = "#525674"
color11 = "#FF6E6E"
color12 = "#69FF94"
color13 = "#FFFFA5"
color14 = "#D6ACFF"
color15 = "#FF92DF"
color16 = "#A4FFFF"
color17 = "#FFFFFF"
