#!/usr/bin/env sh

if [ "$#" -eq 0 ]; then
	awk '{print $1}' ~/.config/web/query
else
	grep -E "^$1   " ~/.config/web/query |
		awk '{print $2}' |
		sed -E 's/\{\}/'"$(xsel -o -p | urlencode  | sed 's#/#\\/#g')"'/' |
		xargs -I {} spawn browse "{}" >/dev/null 2>&1
fi
