#!/usr/bin/env sh

if test "$#" -eq 0; then
	printf '%s\n' "*"
elif test "$#" -eq 1; then
	sleep 0.5
	if test -z "$1"; then
		printf ''
	else
		curl -s -H 'Accept: application/json' "https://api.github.com/search/repositories?q=$(printf '%s' "$1" | jq --slurp --raw-input --raw-output @uri)" | jq -r '.items.[] | .full_name + "   " + .description' | sed 's/   /   '$'\e[1;34m''/;s/$/'$'\e[0m''/'
	fi
elif [ "$#" -eq 2 ]; then
	spawn xdg-open "https://github.com/${2%%   *}"
fi