#!/usr/bin/env sh

if test "$#" -eq 0; then
	printf '%s\n' "*"
elif test "$#" -eq 1; then
	if test -z "$1"; then
		printf ''
	else
		curl -s -H 'Accept: application/json' "https://api.github.com/search/repositories?q=$(printf '%s' "$1" | jq --slurp --raw-input --raw-output @uri)" | jq -r '.items.[].full_name'
	fi
elif [ "$#" -eq 2 ]; then
	spawn xdg-open "https://github.com/$2"
fi