#!/usr/bin/env bash

if [ "$#" -eq 0 ]; then
	jq -r '.roots.other.children[] | select(.name == "query") | .children[] | .name' ~/.config/microsoft-edge/Default/Bookmarks
elif [ "$#" -eq 1 ]; then
	printf '%s\n' "input?"
else
	spawn xdg-open "$(jq -r '.roots.other.children[] | select(.name == "query") | .children[] | select(.name == "'"$1"'") | .url' ~/.config/microsoft-edge/Default/Bookmarks)$(printf "$3" | jq --slurp --raw-input --raw-output @uri)"
fi
