#!/usr/bin/env python3

import curses
import subprocess

screen = curses.initscr()
curses.curs_set(0)
curses.noecho()
curses.start_color()
curses.init_pair(1, curses.COLOR_RED, curses.COLOR_WHITE)
curses.init_pair(2, curses.COLOR_RED, curses.COLOR_MAGENTA)
curses.init_pair(3, curses.COLOR_RED, curses.COLOR_RED)

while True:
    height, width = screen.getmaxyx()
    if height < 5 or width < 60:
        screen.addstr(0, 0, "too small")
    else:
        x = int((width - 50) / 2)
        y = int((height - 3) / 2)
        output = subprocess.check_output(["pactl", "get-sink-volume", "0"]).decode()
        percents = [int(output[pos-3:pos]) for pos, char in enumerate(output) if char == "%"]
        num = int(sum(percents) / len(percents) / 2)
        mute = subprocess.check_output(["pactl", "get-sink-mute", "0"]).decode()[-4:-1]
        screen.addstr(y, x, "                      volume                      ")
        if mute == " no":
            screen.addstr(y + 2, x, " " * num, curses.color_pair(2))
        else:
            screen.addstr(y + 2, x, " " * num, curses.color_pair(3))
        screen.addstr(y + 2, x + num, " " * (50 - num), curses.color_pair(1))
    screen.refresh()
    key = screen.getkey()
    if key == "q":
        break
    elif key == "h":
        subprocess.check_output(["pactl", "set-sink-volume", "0", "-2%"])
    elif key == "l":
        subprocess.check_output(["pactl", "set-sink-volume", "0", "+2%"])
    elif key == "m":
        subprocess.check_output(["pactl", "set-sink-mute", "0", "toggle"])
    screen.clear()

# Restore the terminal settings
curses.endwin()
