#!/usr/bin/env bash

if [ "$#" -eq 0 ]; then
	jq -r '.roots.other.children[] | select(.name == "bookmark") | .children[] | .name' ~/.config/microsoft-edge/Default/Bookmarks
elif [ "$#" -eq 1 ]; then
	spawn xdg-open "$(jq -r '.roots.other.children[] | select(.name == "bookmark") | .children[] | select(.name == "'"$1"'") | .url' ~/.config/microsoft-edge/Default/Bookmarks)"
fi
