#!/usr/bin/env bash

if [ "$#" -eq 0 ]; then
    echo "$XDG_DATA_HOME:$XDG_DATA_DIRS" \
    | tr ":" "\n" \
    | sed 's#$#/applications#' \
    | while read line; do
        if test -d "$line"; then
            cd "$line"
            fd -e desktop | xargs grep "Type=Application" | sed 's#.desktop:Type=Application$##'
        fi
    done
else
    spawn gtk-launch "$1"
fi