#!/usr/bin/env python3

import curses
import subprocess

screen = curses.initscr()
curses.curs_set(0)
curses.noecho()
curses.start_color()
curses.init_pair(1, curses.COLOR_RED, curses.COLOR_WHITE)
curses.init_pair(2, curses.COLOR_RED, curses.COLOR_MAGENTA)
two = int(int(subprocess.check_output(["brightnessctl", "max"]).decode()) / 50)

while True:
    height, width = screen.getmaxyx()
    if height < 5 or width < 60:
        screen.addstr(0, 0, "too small")
    else:
        x = int((width - 50) / 2)
        y = int((height - 3) / 2)
        num = int(int(subprocess.check_output(["brightnessctl", "get"]).decode()) / two)
        screen.addstr(y, x, "                    backlight                     ")
        screen.addstr(y + 2, x, " " * num, curses.color_pair(2))
        screen.addstr(y + 2, x + num, " " * (50 - num), curses.color_pair(1))
    screen.refresh()
    key = screen.getkey()
    if key == "q":
        break
    elif key == "h":
        subprocess.check_output(["brightnessctl", "set", "2%-"])
    elif key == "l":
        subprocess.check_output(["brightnessctl", "set", "+2%"])
    screen.clear()

# Restore the terminal settings
curses.endwin()
