#!/usr/bin/env sh

if test "$#" -eq "0"; then
	echo "lock"
	echo "logout"
	echo "poweroff"
	echo "reboot"
else
	case "$1" in
	lock)
		xautolock -locknow >/dev/null 2>&1
		;;
	logout)
		awesome-client "awesome.quit()" >/dev/null 2>&1
		;;
	poweroff)
		sudo systemctl poweroff >/dev/null 2>&1
		;;
	reboot)
		sudo systemctl reboot >/dev/null 2>&1
		;;
	esac
fi
