theme = "dracula-custom"

[editor]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
tab = "all"
space = "none"
nbsp = "none"
nnbsp = "none"
newline = "all"

[editor.whitespace.characters]
tab = "<"
tabpad = "-"
newline = "↙"

[editor.statusline]
left = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position"]
